# This workflow will install Python dependencies (including the latest RC
# for pysat packages) and run tests for supported operating systems.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: Test with pysat ecosystem RCs

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
        rc-package: ["pysat", "pysatNASA"]

    name: ${{ matrix.os }} with ${{ matrix.rc-package }} RC
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install RC package
      run: pip install --no-deps --pre -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ ${{ matrix.rc-package }}

    - name: Install standard dependencies
      run: |
        pip install -r test_requirements.txt
        pip install -r requirements.txt

    - name: Set up pysat
      run: |
        mkdir pysatData
        python -c "import pysat; pysat.params['data_dirs'] = 'pysatData'"

    - name: Run unit and integration tests
      run: pytest --cov=pysatModels/

    - name: Publish results to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
